// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8YvHKjya0yI1LS8iirteD--_lVGJTBS4',
    appId: '1:383321204455:web:d5fdbefd73f82079d5e442',
    messagingSenderId: '383321204455',
    projectId: 'pravez-nature-call',
    authDomain: 'pravez-nature-call.firebaseapp.com',
    storageBucket: 'pravez-nature-call.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxRDukEUrzDzQUn11VSrfUEmteeoHwm3w',
    appId: '1:383321204455:android:e3a01e1bfb5f2c8ad5e442',
    messagingSenderId: '383321204455',
    projectId: 'pravez-nature-call',
    storageBucket: 'pravez-nature-call.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-QjDxAEeLufNLsQ-PARCifJ2Wlzj626U',
    appId: '1:383321204455:ios:9c4800382ca95fd9d5e442',
    messagingSenderId: '383321204455',
    projectId: 'pravez-nature-call',
    storageBucket: 'pravez-nature-call.appspot.com',
    iosClientId: '383321204455-puf43p84acvin8cuvj0n2fakn3ccg5af.apps.googleusercontent.com',
    iosBundleId: 'com.pravez.naturesCall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-QjDxAEeLufNLsQ-PARCifJ2Wlzj626U',
    appId: '1:383321204455:ios:9c4800382ca95fd9d5e442',
    messagingSenderId: '383321204455',
    projectId: 'pravez-nature-call',
    storageBucket: 'pravez-nature-call.appspot.com',
    iosClientId: '383321204455-puf43p84acvin8cuvj0n2fakn3ccg5af.apps.googleusercontent.com',
    iosBundleId: 'com.pravez.naturesCall',
  );
}
